[theme]
primaryColor = "#ff9800"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
port = 7777
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
